# Generated by Django 5.2.7 on 2025-10-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0002_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='dificultad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
